# Setup
name:         Jevan Wu's Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-mermaid

mermaid:
  src: "/assets/mermaid.min.js"

url: "https://jevanwu.github.io/"

jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    category: '/categories/:name/'

#Others
markdown: kramdown

